# Generated by Django 4.2.13 on 2024-08-25 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.TextField(blank=True, null=True)),
                ('age', models.TextField(blank=True, null=True)),
                ('country', models.TextField(blank=True, null=True)),
                ('county', models.TextField(blank=True, null=True)),
                ('income', models.TextField(blank=True, null=True)),
                ('cstatus', models.TextField(blank=True, null=True)),
                ('education', models.TextField(blank=True, null=True)),
                ('marital', models.TextField(blank=True, null=True)),
                ('goals', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
